version: '3.9'
services:

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ./database-data:/var/lib/postgresql/data/



  web:
    build: .
    ports:
      - "7500:7500"
