# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:latest


    steps:
      - checkout

     # - run: clojure

      # run tests!
      - run: ls
      - run: cd patient-frontend
      - run: clojure -M:test


