# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:latest

      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: georgii
          - POSTGRES_PASSWORD: blank
          - POSTGRES_DB: test_patient
    steps:
      - checkout
      - run:
          name: install Dockerize
          command: |
            wget http://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION
            dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/ 
            bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: sudo apt update && sud apt install psql
      - run: ls
      - run: psql createuser georgii && cd patient-api && clojure -M:test -d test
