#
# https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 1
jobs:
  build:

    working_directory: ~/patient-frontend

    steps:

      # run tests!
      - run: clj -M:test -d test -n test-helpers 

