# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:latest

      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: georgii
          - POSTGRES_PASSWORD: blank
          - POSTGRES_DB: test_patient
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: sudo apt update && sud apt install psql
      - run: ls
      - run: psql createuser georgii && cd patient-api && clojure -M:test -d test
