# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:latest

    working_directory: ~/patient-frontend

    steps:
      - checkout

      - run: clj

      # run tests!
      - run: clj -M:test -d test -n test-helpers


