name: App tester

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: '1.10.1.469'
      - run: clojure -Sdescribe
      - run: docker-compose up  

      # - name: Docker compose
      #   run: docker-compose up -d
      # - name: Run tests
      #   run: cd patient-api && clj -M:test -d test -n app.utils
