name: App tester

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: '1.10.1.697'

      - name: Run tests
        run: make test-backend
        run: make test-frontend
